/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
    kPIN_MUX_DirectionInput = 0U,        /* Input direction */
    kPIN_MUX_DirectionOutput = 1U,       /* Output direction */
    kPIN_MUX_DirectionInputOrOutput = 2U /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PIO1_0 (number 11), Green_LED
  @{ */
#define BOARD_INITPINS_Green_LED_PERIPHERAL SCT0   /*!<@brief Device name: SCT0 */
#define BOARD_INITPINS_Green_LED_SIGNAL OUT        /*!<@brief SCT0 signal: OUT */
#define BOARD_INITPINS_Green_LED_PORT 1U           /*!<@brief PORT device name: 1U */
#define BOARD_INITPINS_Green_LED_PIN 0U            /*!<@brief 1U pin index: 0 */
#define BOARD_INITPINS_Green_LED_CHANNEL 2         /*!<@brief SCT0 OUT channel: 2 */
#define BOARD_INITPINS_Green_LED_PIN_NAME PIO1_0   /*!<@brief Pin name */
#define BOARD_INITPINS_Green_LED_LABEL "Green_LED" /*!<@brief Label */
#define BOARD_INITPINS_Green_LED_NAME "Green_LED"  /*!<@brief Identifier name */
                                                   /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M0P */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
