#ifndef __SCT_FSM_H__
#define __SCT_FSM_H__

/* Generated by fzmparser version 2.4 --- DO NOT EDIT! */

#include "sct_user.h"

extern void sct_fsm_init (void);

/* Output assignments (and their defaults if specified) */
#define SCT_OUTPUT_Output_pin_0 (0)
#define SCT_OUTPUTPRELOAD_Output_pin_0 (0)

#define SCT_setOutputDefault() do {LPC_SCT->OUTPUT = (LPC_SCT->OUTPUT & ~0x00000001) | 0x00000000;} while(0)


/* Match register reload macro definitions */
#define reload_match_0_(value) do {LPC_SCT->MATCHREL[0].U = value;} while(0)

#endif
